# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mitsch's Blog
email: michael.koch@mailbox.org
description: > # this means to ignore newlines until "baseurl:"
  My attempt of getting more into technical writing as well technical story
  telling. I will try to cover few areas. Hopefully, blogging here will not
  only help me to clear my head, but also deliver somebody outside good help.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: KochMitsch
github_username:  mitsch

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman